### PR TITLE
Add OHC examples to CircleCI

### PR DESCRIPTION
**Pull request by bonnland**
Do the notebooks look OK?   I deleted the cell output from one tutorial because it changed, due to the data temporal coverage not being the same as the original file.

### CODE REVIEW

**Comment by bonnland** [comment]
I'm not sure that the parallelism is working properly on CircleCI.   The main constraint appears to be RAM, so it's going to be important to try to split the runs across multiple machines if possible.

**Comment by bonnland** [comment]
@jukent @andersy005 Please review.  The example works, but I am not clear on whether keeping the rendered output in the notebooks is important.  Do either of you have an opinion on this?

**Comment by andersy005** [comment]
> The example works, but I am not clear on whether keeping the rendered output in the notebooks is important. Do either of you have an opinion on this?

I am in favor of stripping output from the notebooks prior merging.

**Review by andersy005 — APPROVED** [review]

**Review by jukent — APPROVED** [review]

**Comment by maboualidev** [comment]
LGTM

**Pull request merged**
