### PR TITLE
Use distributed pytest

### PR DESCRIPTION
**Pull request by bonnland**
It's not a big change, but I think it's going to speed up testing.  

I hope we can add the other notebooks in the gallery soon.

### CODE REVIEW

**Review by andersy005 — APPROVED** [review]
Looks good to me!

**Comment by bonnland** [comment]
Three notebooks were tested in just over three minutes.   A big speedup!

**Review by jukent — APPROVED** [review]

**Comment by andersy005** [comment]
@bonnland, is this ready to be merged?

**Comment by bonnland** [comment]
Yes, I forgot to check it!  Thanks for the reminder.

**Review by maboualidev — COMMENTED** [review]
LGTM

**Pull request merged**
