### PR TITLE
Update environment & notebooks

### PR DESCRIPTION
**Pull request by andersy005**

### CODE REVIEW

**Comment by bonnland** [comment]
@andersy005 Is the updated environment working for the MPAS example?   Is there a way I could confirm this if I needed to?  I am unclear on how I can apply a draft pull request for testing to my own cloned repo.

**Comment by dcherian** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

**Comment by bonnland** [comment]
Thanks Deepak!  @andersy005 What do you think about adding a version string to the conda environment?   Like, for example, notebook-gallery-2019_11_12.   That way, we can deal with evolution of the conda environment more cleanly.

**Comment by bonnland** [comment]
@andersy005  You can remove the white line in the final plot by adding this line to the notebook, before calculating the triangulation.   It maps longitude to the range [-180, 180] from [0, 360]:

ds["lonCell"] = ((ds["lonCell"] + 180) % 360) - 180

**Comment by andersy005** [comment]
For some reason unbeknownst to me, TravisCI is reporting

```
ftplib.error_temp: 425 Security: Bad IP connecting.
```

My speculation is that there is some strange network translation going on inside TravisCI when accessing ftp servers and I don't know how to address it (I am going to try CircleCI)

**Comment by andersy005** [comment]
> For some reason unbeknownst to me, TravisCI is reporting
> 
> ```
> ftplib.error_temp: 425 Security: Bad IP connecting.
> ```
> 
> My speculation is that there is some strange network translation going on inside TravisCI when accessing ftp servers and I don't know how to address it (I am going to try CircleCI)

Since [CircleCI appears to be working fine](This is ready to be merged! 

https://app.circleci.com/jobs/github/NCAR/notebook-gallery/3), it's my understanding that there's some strange behavior going on at TravisCI level

**Review by bonnland — APPROVED** [review]
The tests pass for me on cheyenne.  I approve 100%.

**Pull request merged**
