### PR TITLE
Cleaned up and annotated notebooks I contributed to gallery

### PR DESCRIPTION
**Pull request by jukent**
OHC
WRF
and bias-correction

Addresses #60

### CODE REVIEW

**Review by andersy005 — COMMENTED** [review]
This is looking great, @jukent

Do we need this notebook cell?

> Or if not on Cheyenne hist_file = DATASERTS.fetch("/uas.hist.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc") rcp85_file = DATASERTS.fetch("/uas.rcp85.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc") meas_file = DATASETS.fetch("uas.gridMET.NAM-44i.Colorado.nc")

**Comment by jukent** [comment]
No perhaps we can we assume we are on Cheyenne. I will delete that cell @andersy005 Though I can't find that cell. It looks like it is from the bias-correction notebook.

E: Ahh I see it. I edited the bias-correction within the Run Anywhere folder. The separate Bias-Correction folder has some methods that can be removed from the repo.

**Review by andersy005 — APPROVED** [review]
Thank you, Julia! This is ready to be merged in my opinion. 

Ccing @NCAR/xdev-education just in case they have additional input/feedback

**Review by bonnland — APPROVED** [review]
Thank you Julia, these notebooks look good.

**Pull request merged**
