### PR TITLE
corrected time groupings in bias correction

### PR DESCRIPTION
**Pull request by jukent**

### CODE REVIEW

**Comment by andersy005** [comment]
@jukent, can you pull and merge latest changes from the master branch into your master branch? Last night, I fixed the issue that was causing this PR to fail.

**Review by andersy005 — COMMENTED** [review]
@jukent 

It appears that there are some unnecessary dask files that are included in the PR. Can you delete the

dask-worker-space directory:

```bash
rm -rf  Bias-Correction/dask-worker-space/
```

And  `dask-worker-space/` entry to the `.gitignore` so that these files are ignored in the future?

**Comment by jukent** [comment]
Done

**Comment by dcherian** [comment]
@jukent these figures look great.

Is there a reason you chose to do
``` python
plt.contourf(ds_hist.lon, ds_hist.lat, ds_hist[var].isel(time=0), norm=MidpointNormalize(midpoint=0.), cmap='PRGn')
cbar = plt.colorbar()
cbar.set_label('m / s', size=15)
```
instead of
``` python
ds_hist[var].isel(time=0).plot(x="lon", y="lat", cmap="PRGn", cbar_kwargs={"label": "m/s"})
```

Barring a bug, those should be exactly the same with a lot less typing :)

**Comment by jukent** [comment]
Would that set the colormap midpoint?

**Comment by dcherian** [comment]
Yup :) https://xarray.pydata.org/en/stable/plotting.html#two-dimensions Look at the colorbar in the first figure.

You can change the center point with the `center` kwarg

(the ridiculously easy plotting was why I loved xarray to begin with)

**Comment by jukent** [comment]
I'll update the plotting method!

**Comment by jukent** [comment]
Doing this plotting method has a pixelated look, versus a smooth contour.
Screen Shot 2019-11-21 at 3 08 13 PM
Screen Shot 2019-11-21 at 3 08 08 PM

**Comment by dcherian** [comment]
Use `.plot.contourf` By default it uses `pcolormesh` for speed.

**Comment by jukent** [comment]
Created a new pull request #33

**Pull request merged**
