### PR TITLE
Added WRF data to registry.txt and data.py

### PR DESCRIPTION
**Pull request by jukent**

### CODE REVIEW

**Review by bonnland — CHANGES_REQUESTED** [review]
@jukent Hi Julia, if you want, you could move (git move) the WRF directory into the folder Run-Anywhere as part of your pull request.  Then the notebook will automatically be tested for correctness.

**Review by maboualidev — APPROVED** [review]

**Review by maboualidev — APPROVED** [review]

**Comment by jukent** [comment]
It is failing saying that the two new files are not in the registry. But the registry file is changed to include them. Any insight on this? @bonnland @andersy005 @maboualidev

**Comment by andersy005** [comment]
This line https://github.com/NCAR/notebook-gallery/blob/ce4bb491175e4539cdae9d6431e3673d5c3df4d2/.circleci/config.yml#L30 is the culprit. The `enviroment.yml` file points to the master branch of `notebook-gallery`:
https://github.com/NCAR/notebook-gallery/blob/ce4bb491175e4539cdae9d6431e3673d5c3df4d2/environment.yml#L53

This means that when the environment is being created, changes from the pull request are not being ignored.  

Running `pip install` after the environment creation should address the issue

```yaml
conda env update -f environment.yml -q
source activate ${ENV_NAME}
python -m pip install . 
```

**Review by maboualidev — APPROVED** [review]

**Comment by bonnland** [comment]
@jukent @andersy005   I was the one who commented out the "pip install" line.   The reason was to give a way of knowing the BinderHub version of the gallery would successfully install.   I wanted to put all install-related commands in environment.yml, since BinderHub and CircleCI would both use this file to build the environment.

Is the plan, then, to approve the pull request for now, so that the master branch has the correct registry?

**Pull request merged**
