### PR TITLE
Add aws catalog for NA-CORDEX

### PR DESCRIPTION
**Pull request by bonnland**
Stakeholders have asked for notebook examples showing AWS data being accessed via intake catalog.   

This notebook is updated to include intake catalog search.

### CODE REVIEW

**Comment by andersy005** [comment]
@bonnland, I'm wondering whether the contents of this PR should reside in https://github.com/NCAR/na-cordex-aws instead? It'd be nice to start populating that repo with some relevant contents prior the official dataset announcement.

**Comment by bonnland** [comment]
@andersy005  It is a good point; the need for access to Glade is a potential problem.

It is also a nice example of how you can access Amazon data from your local laptop environment.

I could see us creating a similar notebook for https://github.com/NCAR/na-cordex-aws.  If there is some kind of timing comparison that does not involve Glade, that would be ideal.

**Comment by bonnland** [comment]
@andersy005 I will add a version of this notebook that does not compare timings to the https://github.com/NCAR/na-cordex-aws repo.   It will simply produce the diagnostic plots from the AWS stores.

Thanks for the idea!

**Review by andersy005 — APPROVED** [review]

**Comment by bonnland** [comment]
There are extra bells and whistles I could add to this notebook, such as functions to produce PNG and PDF output for the plots.   I will add these in a separate PR as time to make the notebook public gets closer.

**Pull request merged**
