### PR TITLE
Add HPC-related packages and fix markdown headers

### PR DESCRIPTION
**Pull request by bonnland**
1.  Change the conda environment to include tools needed for running on Casper/Cheyenne.

2.  Fix notebook markdown so that pangeo-gallery parses notebooks correctly for Sphinx documentation.

This page shows that the notebook parsing is not working as expected right now:  

http://gallery.pangeo.io/repos/NCAR/notebook-gallery/index.html

### CODE REVIEW

**Comment by bonnland** [comment]
@andersy005  I am not sure the branch should be deleted yet.   I am trying to understand if the binderbot build will be triggered by merge, so that the pangeo-gallery renderings will be updated.   

Also, I am trying to figure out if there is a way to show the rendered notebook outputs in pangeo-gallery using binderbot.

**Comment by andersy005** [comment]
> I am trying to understand if the binderbot build will be triggered by merge, so that the pangeo-gallery renderings will be updated 

It appears that the latest changes didn't trigger binderbot, and the problem is this line 

https://github.com/NCAR/notebook-gallery/blob/d0c8cadf8de010fb4203f76e8dbfb9d1311286cf/.github/workflows/binderbot.yaml#L9

I don't think this regex is correct.

**Comment by andersy005** [comment]
My recommendation is to comment those path filters for the time being

**Comment by andersy005** [comment]
> Also, I am trying to figure out if there is a way to show the rendered notebook outputs in pangeo-gallery using binderbot. 

gallery.pangeo.io renders new versions when binderbot builds (from the main branch) have succeeded.

**Pull request merged**
