### PR TITLE
Update build to use main branch

### PR DESCRIPTION
**Pull request by bonnland**

### CODE REVIEW

**Comment by kmpaul** [comment]
@bonnland:  The binderbot test is failing due to the following errors:

- error running notebooks/Run-Anywhere/mpas/plot_of_surface_pressure_on_mpas_grid>
  - NoSuchKernel: No such kernel named conda-env-notebook-gallery-py

    This error can be fixed by changing the following section in the Notebook `metadata` JSON section from:

    ```json
    "kernelspec": {
       "display_name": "Python [conda env:notebook-gallery]",
       "language": "python",
       "name": "conda-env-notebook-gallery-py"
      }
    ```
    
    to:
    
    ```yaml
    "kernelspec": {
       "display_name": "Python 3",
       "language": "python",
       "name": "python3"
    }
    ```

- error running notebooks/Run-Anywhere/mpas/plot_terrain.ipynb
  - OSError: ./MPL_terrain.rgb not found.

    This error is related to the deficiency in binderbot related to this issue:

    https://github.com/pangeo-gallery/binderbot/issues/28

**Comment by kmpaul** [comment]
I suppose that one solution to this problem might be to move the `notebooks/Run-Anywhere/mpas/plot_terrain.ipynb` notebook to another directory so that it is not part of the Binder notebook gallery, and then add it back in when https://github.com/pangeo-gallery/binderbot/issues/28 gets fixed.

**Comment by bonnland** [comment]
Thanks, Kevin!  I will give your suggestions a try.  

Out of curiosity, how did you figure out how to fix the kernel JSON issue?

**Comment by kmpaul** [comment]
Well, I knew that `ipynb` files are specially formatted JSON files, and that the `metadata` section of those JSON files contain information about the Notebook itself, including information about the kernel the notebook expects to find when executed. 

So, I just looked at the `metadata` section in the other notebooks that were running properly to see what actually worked.

**Comment by bonnland** [comment]
That makes sense, I hadn't thought about checking other notebooks, thanks!

@andersy005  Is it worth fixing the binderbot failure before merging this PR, or is it OK to go ahead?

**Comment by kmpaul** [comment]
The Binderbot errors now appear to be related to the "Trigger repository dispatch on Pangeo Gallery" step of the Binderbot GitHub Action.  In particular, it appears to be an error running this command as the last step of the `.github/workflows/binderbot.ym:

```
      - name: Trigger repository dispatch on Pangeo Gallery
        run: curl -f https://pangeo-gallery-bot.herokuapp.com/gallery/submodule-dispatch/${{ github.repository }}
```

where `${{ github.repository }}` is being translated as `NCAR/notebook-gallery`.  i.e.:

```
curl -f https://pangeo-gallery-bot.herokuapp.com/gallery/submodule-dispatch/NCAR/notebook-gallery
```

which appears to receive a 500 Internal Server Error response.  Does this step in the GitHub Action need to be modified or fixed somehow?

**Comment by bonnland** [comment]
> a 500 Internal Server Error response. Does this step in the GitHub Action need to be modified or fixed somehow?

I don't know what used to happen on this step, but a 500 Internal Server Error suggests to me that something outside our control is no longer working.

**Comment by andersy005** [comment]
The dispatch error is due to the fact that this repo hasn't been registered in the pangeo gallery yet. To register this repository, some will need to follow the contributing guide here: http://gallery.pangeo.io/contributing.html

**Comment by andersy005** [comment]
> The dispatch error is due to the fact that this repo hasn't been registered in the pangeo gallery yet. To register this repository, some will need to follow the contributing guide here: http://gallery.pangeo.io/contributing.html


More specifically, the submodule step: http://gallery.pangeo.io/contributing.html#add-a-submodule-via-git

**Comment by bonnland** [comment]
> To register this repository, some will need to follow the contributing guide here: http://gallery.pangeo.io/contributing.html

I will open a PR now.

**Comment by rabernat** [comment]
I'm going to drop in here to understand what is going on better.

How are you generating your binderbot-built branch? https://github.com/NCAR/notebook-gallery/tree/binderbot-built

It is identical to main. It doesn't look like the usual output of binderbot's build process.

**Comment by bonnland** [comment]
I used that branch because this repo already had a binderbot-gallery.yaml file created by someone else, with that as the branch name.   Not being the one who originally set all of this up, I was making the most conservative configuration change I could to start with.

**Comment by bonnland** [comment]
The multitude of GitHub features are awesome, until you have to deeply understand what someone else has set up...

**Comment by rabernat** [comment]
So binderbot is not committing your notebooks to your repo because, so far, it has only run on a PR branch, not on the master branch.

I recommend you delete the `binderbot-built` branch that you created manually, then merge this PR and let binderbot do its thing.

**Comment by bonnland** [comment]
OK, thanks Ryan, I will try that now.

**Comment by rabernat** [comment]
It looks like the binderbot workflow failed because of a timeout

https://github.com/NCAR/notebook-gallery/runs/1818215323?check_suite_focus=true

edit: it's puzzling to me why this didn't happen during the PR run, which seemed to execute fine. You can get around this error by increasing your timeouts in the workflow

https://github.com/NCAR/notebook-gallery/blob/ceb680d62ac08880c12cae971f9b987a5c3ac16d/.github/workflows/binderbot.yaml#L63-L70

The default timeout is 600 seconds (10 minutes)
https://github.com/pangeo-gallery/binderbot/blob/32c96df4f56857bb1c4f7676ef9323a173aed677/binderbot/cli.py#L29-L30

You could add an extra flag to extend this.

**Comment by bonnland** [comment]
It seems like the timeout happened much faster than 10 minutes, though I wasn't staring at a watch or anything...

**Comment by rabernat** [comment]
Try rerunning the workflow manually (this should be an option available to admins on this repo).

image

**Comment by bonnland** [comment]
@andersy005 @kmpaul   Somehow I have the admin role for this repo, but the option to trigger workflows is missing from my user interface.   Is this a side effect of our bot configuration, perhaps?

**Comment by bonnland** [comment]
I also lack the ability to let others push to this PR, which is equally odd.

**Comment by bonnland** [comment]
@kmpaul @andersy005   Sorry, I was on the wrong page apparently, and I was able to retrigger the workflows after all.

**Comment by bonnland** [comment]
@rabernat Below is the error from re-running the workflow.   It is the same error we got that led to me opening the pangeo-gallery PR.

```
Run curl -f https://pangeo-gallery-bot.herokuapp.com/gallery/submodule-dispatch/NCAR/notebook-gallery
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
curl: (22) The requested URL returned error: 500 Internal Server Error
```

**Comment by rabernat** [comment]
I am not seeing the workflow as having been re-run: https://github.com/NCAR/notebook-gallery/actions?query=workflow%3ABinderbot

The last run was one hour ago and ended with the timeout: https://github.com/NCAR/notebook-gallery/runs/1818215323?check_suite_focus=true

**Comment by rabernat** [comment]
> It is the same error we got that led to me opening the pangeo-gallery PR.

This error is ignorable. It's a weird chicken-and-egg problem with the pangeo-gallery repo. It won't work until the pangeo gallery PR (https://github.com/pangeo-gallery/pangeo-gallery/pull/48) is merged.

**Comment by bonnland** [comment]
Screen Shot 2021-02-02 at 3 59 07 PM

I just clicked that Re-Run All Jobs button...

**Comment by bonnland** [comment]
The notebooks are executing successfully.   But if this run goes as it did last time, it will fail with that ignorable error you mentioned.

**Comment by bonnland** [comment]
The ignorable error happened, and the last two steps of the workflow were not executed.   It should show that it just ran now.

**Comment by rabernat** [comment]
Yes the notebooks are executing successfully. But they are not being committed to the `binderbot-built` branch. That's because those steps only run when the workflow is triggered from the master branch (like after merging a PR) and not from the PR branch.

https://github.com/NCAR/notebook-gallery/blob/ceb680d62ac08880c12cae971f9b987a5c3ac16d/.github/workflows/binderbot.yaml#L71-L80

You are re-running the workflow from a PR branch:

https://github.com/NCAR/notebook-gallery/actions?query=branch%3Amain

You need to run the workflow on the master branch in order to trigger the commit:

Another problem is that the workflow assumes your branch is called `master`, but this repo uses `main`. So that needs to be made consistent.

**Pull request merged**
