### PR TITLE
Update data.py

### PR DESCRIPTION
**Pull request by jukent**
Added URLs for zscore bias correction data

### CODE REVIEW

**Comment by andersy005** [comment]
@jukent, 

I noticed that  the checksums for both `uas.hist.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc`, `uas.rcp85.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc` are exactly the same:

https://github.com/NCAR/notebook-gallery/blob/f5ba557be1751e105037737640940ec3fb725a0b/ngallery_utils/registry.txt#L13-L14


And this suggests that the two datasets are identical. I can confirm that these two datasets are exactly the same:

```python
In [1]: import xarray as xr                                                                                                                                                                                

In [2]: hist = xr.open_dataset("uas.hist.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc")                                                                                                                  

In [3]: rcp85 = xr.open_dataset("uas.rcp85.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc")                                                                                                                

In [4]: xr.testing.assert_identical(hist, rcp85)                                                                                                                                                           

```

Is this intentional?

**Comment by jukent** [comment]
> @jukent,
> 
> I noticed that the checksums for both `uas.hist.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc`, `uas.rcp85.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc` are exactly the same:
> 
> https://github.com/NCAR/notebook-gallery/blob/f5ba557be1751e105037737640940ec3fb725a0b/ngallery_utils/registry.txt#L13-L14
> 
> And this suggests that the two datasets are identical. I can confirm that these two datasets are exactly the same:
> 
> ```python
> In [1]: import xarray as xr                                                                                                                                                                                
> 
> In [2]: hist = xr.open_dataset("uas.hist.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc")                                                                                                                  
> 
> In [3]: rcp85 = xr.open_dataset("uas.rcp85.CanESM2.CRCM5-UQAM.day.NAM-44i.raw.Colorado.nc")                                                                                                                
> 
> In [4]: xr.testing.assert_identical(hist, rcp85)                                                                                                                                                           
> ```
> 
> Is this intentional?

They are the same. They are the datasets Seth pointed me too. The future model wasn't important for testing the algorithm, but I am suspicious or skeptical that it is the best example.

**Comment by andersy005** [comment]
They also appear to be spanning the same time range:

```python
In [8]: rcp85.time                                                                                                                                                                                                                                                      
Out[8]: 
<xarray.DataArray 'time' (time: 20440)>
array([cftime.DatetimeNoLeap(1950-01-01 12:00:00),
       cftime.DatetimeNoLeap(1950-01-02 12:00:00),
       cftime.DatetimeNoLeap(1950-01-03 12:00:00), ...,
       cftime.DatetimeNoLeap(2005-12-29 12:00:00),
       cftime.DatetimeNoLeap(2005-12-30 12:00:00),
       cftime.DatetimeNoLeap(2005-12-31 12:00:00)], dtype=object)
Coordinates:
  * time     (time) object 1950-01-01 12:00:00 ... 2005-12-31 12:00:00
Attributes:
    actual_range:        [ 31.5 395.5]
    coordinate_defines:  point
    bounds:              time_bnds
    delta_t:             0000-00-01 00:00:00
    axis:                T
    standard_name:       time
    long_name:           time

In [9]: hist.time                                                                                                                                                                                                                                                       
Out[9]: 
<xarray.DataArray 'time' (time: 20440)>
array([cftime.DatetimeNoLeap(1950-01-01 12:00:00),
       cftime.DatetimeNoLeap(1950-01-02 12:00:00),
       cftime.DatetimeNoLeap(1950-01-03 12:00:00), ...,
       cftime.DatetimeNoLeap(2005-12-29 12:00:00),
       cftime.DatetimeNoLeap(2005-12-30 12:00:00),
       cftime.DatetimeNoLeap(2005-12-31 12:00:00)], dtype=object)
Coordinates:
  * time     (time) object 1950-01-01 12:00:00 ... 2005-12-31 12:00:00
Attributes:
    actual_range:        [ 31.5 395.5]
    coordinate_defines:  point
    bounds:              time_bnds
    delta_t:             0000-00-01 00:00:00
    axis:                T
    standard_name:       time
    long_name:           time
```

**Comment by jukent** [comment]
They seem to be identical files. This is fine for an example, but I will talk to Seth about it.

**Pull request merged**
