### PR TITLE
WRF example

### LINKED ISSUE #20: WRF data example
WRF metadata is formatted in a way not-easily read by Xarray. Ultimately we want to edit Xarray to understand these datasets, but let's create an example work around for WRF data time, lat, and lon coordinates, and how to plot data where x and y are 2-D. I have emailed Trude Eldhammer about using the notebook we worked on together during the tutorial as the example.

### PR DESCRIPTION
**Pull request by jukent**
Closes #20

### CODE REVIEW

**Review by andersy005 — COMMENTED** [review]
How big is the input file? If it's not big, can we include it in the repo? If it's big but is publicly available online, can we do what I did in [MPAS notebook](https://github.com/NCAR/notebook-gallery/blob/master/mpas/plot_of_surface_pressure_on_mpas_grid.ipynb) by including a cell to download the data

```python
!mkdir -p ../data/ncl_data && wget https://www.ncl.ucar.edu/Applications/Data/cdf/MPAS.nc -O ../data/ncl_data/MPAS.nc


ds = xr.open_dataset("../data/ncl_data/MPAS.nc")
```



?

**Comment by jukent** [comment]
> How big is the input file? If it's not big, can we include it in the repo? If it's big but is publicly available online, can we do what I did in [MPAS notebook](https://github.com/NCAR/notebook-gallery/blob/master/mpas/plot_of_surface_pressure_on_mpas_grid.ipynb) by including a cell to download the data
> 
> ```python
> !mkdir -p ../data/ncl_data && wget https://www.ncl.ucar.edu/Applications/Data/cdf/MPAS.nc -O ../data/ncl_data/MPAS.nc
> 
> 
> ds = xr.open_dataset("../data/ncl_data/MPAS.nc")
> ```
> 
> ?

The files are on glade at /glade/work/trude/evoglac/idl/NETCDF_files/wrfinput_d02 (about 130 MB) and /glade/work/trude/evoglac/WRF_output_2T_RR_F/all_T2_RR_F_2014_2019_SST.nc (about 15 Gigs)

**Comment by jukent** [comment]
@andersy005  The data is at 
/glade/u/home/jkent/data/all_T2_RR_F_2014_2015_SST.nc

AND

/glade/work/trude/evoglac/idl/NETCDF_files/wrfinput_d02

**Comment by andersy005** [comment]
@jukent, I will put it on the FTP server and will let you know when it's ready

**Pull request merged**
